openapi: "3.1.0"
info:
  title: "ai_poc API"
  description: "ai_poc API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
    description: "Local development server"
paths:
  /api/documents/answer:
    post:
      summary: "POST api/documents/answer"
      operationId: "answer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnswerRequest"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/StreamingResponseBody"
components:
  schemas:
    StreamingResponseBody:
      type: "object"
      properties: { }
    AnswerRequest:
      type: "object"
      required:
        - question
      properties:
        question:
          type: "string"
        fileName:
          type: "string"
        model:
          type: "string"
        maxTokens:
          type: "integer"
          format: "int64"